tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0a0e16",
        "surface-container-low": "#181c24",
        "on-secondary-fixed": "#07006c",
        "surface-container": "#1c2028",
        "on-primary-fixed": "#001e2c",
        "secondary": "#c0c1ff",
        "secondary-fixed-dim": "#c0c1ff",
        "on-secondary": "#1000a9",
        "surface-bright": "#353942",
        "on-tertiary": "#003824",
        "tertiary-fixed-dim": "#4edea3",
        "on-secondary-container": "#b0b2ff",
        "primary-fixed": "#c4e7ff",
        "on-secondary-fixed-variant": "#2f2ebe",
        "on-primary-fixed-variant": "#004c69",
        "secondary-container": "#3131c0",
        "inverse-on-surface": "#2c3039",
        "primary-container": "#38bdf8",
        "on-background": "#dfe2ee",
        "surface": "#0f131c",
        "primary": "#8ed5ff",
        "outline": "#87929a",
        "surface-dim": "#0f131c",
        "on-tertiary-container": "#004e34",
        "outline-variant": "#3e484f",
        "on-error-container": "#ffdad6",
        "surface-variant": "#31353e",
        "on-error": "#690005",
        "on-surface-variant": "#bdc8d1",
        "on-tertiary-fixed": "#002113",
        "surface-container-high": "#262a33",
        "tertiary": "#56e5a9",
        "tertiary-container": "#30c88f",
        "tertiary-fixed": "#6ffbbe",
        "inverse-surface": "#dfe2ee",
        "error": "#ffb4ab",
        "secondary-fixed": "#e1e0ff",
        "inverse-primary": "#00668a",
        "primary-fixed-dim": "#7bd0ff",
        "on-primary": "#00354a",
        "on-surface": "#dfe2ee",
        "background": "#0f131c",
        "surface-tint": "#7bd0ff",
        "surface-container-highest": "#31353e",
        "on-tertiary-fixed-variant": "#005236",
        "on-primary-container": "#004965",
        "error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "margin-mobile": "1rem",
        "gutter": "1.5rem",
        "gutter-mobile": "1rem",
        "margin": "2rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem"
      },
      fontFamily: {
        "headline-lg-mobile": ["Geist"],
        "label-mono-sm": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "label-code": ["JetBrains Mono"],
        "headline-md": ["Geist"],
        "body-md": ["Inter"],
        "display-mobile": ["Geist"],
        "body-lg": ["Inter"],
        "label-ui": ["Inter"],
        "headline-sm": ["Geist"],
        "headline-lg": ["Geist"],
        "display": ["Geist"]
      },
      fontSize: {
        "headline-lg-mobile": ["1.75rem", { "lineHeight": "2.25rem", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-mono-sm": ["0.75rem", { "lineHeight": "1rem", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "body-sm": ["0.875rem", { "lineHeight": "1.375rem", "fontWeight": "400" }],
        "label-code": ["0.875rem", { "lineHeight": "1.25rem", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "headline-md": ["1.5rem", { "lineHeight": "2rem", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "body-md": ["1rem", { "lineHeight": "1.625rem", "fontWeight": "400" }],
        "display-mobile": ["2.5rem", { "lineHeight": "3rem", "letterSpacing": "-0.025em", "fontWeight": "700" }],
        "body-lg": ["1.125rem", { "lineHeight": "1.75rem", "fontWeight": "400" }],
        "label-ui": ["0.875rem", { "lineHeight": "1.25rem", "fontWeight": "500" }],
        "headline-sm": ["1.25rem", { "lineHeight": "1.75rem", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg": ["2.25rem", { "lineHeight": "2.75rem", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "display": ["3.75rem", { "lineHeight": "4.25rem", "letterSpacing": "-0.03em", "fontWeight": "700" }]
      }
    }
  }
};
